// GLOBAL

// POST
export const CLEAR_POST_STATE = "CLEAR_POST_STATE";
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POST = "FETCH_POST";
export const CREATE_POST = "CREATE_POST";
export const LIKE_POST = "LIKE_POST";
export const DISLIKE_POST = "DISLIKE_POST";
export const COMMENT_POST = "COMMENT_POST"
// USER - AUTH
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const RESTORE_ACCOUNT = "RESTORE_ACCOUNT";
export const RESTORE_PASSWORD = "RESTORE_PASSWORD";
export const SIGNUP = "SIGNUP";
export const UPDATE_USER = "UPDATE_USER";
export const CLEAR_USER_STATUS = "CLEAR_USER_STATUS";
// QUESTION

export const CLEAR_QUESTION_STATE = "CLEAR_QUESTION_STATE";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTION = "FETCH_QUESTION";
export const CREATE_QUESTION = "CREATE_QUESTION";
export const ANSWER_QUESTIONS = "ANSWER_QUESTIONS";
export const LIKE_ANSWER = "LIKE_ANSWER";
export const DISLIKE_ANSWER = "DISLIKE_ANSWER";